### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Quick Update to README.md example (foo > bar)

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Related to #7, I just had a few moments and wanted to help in case it was what you were after. Saw your blog, disagree with the way people acted :(

**Comment by sc0ttkclark** [comment]
Also, sorry this wasn't a more substantial contribution. I like your utility, haven't used it yet but I love what it does. I often rely on my IDE to do this, but it's imperfect and doesn't let you replace against specific files that match patterns.

**Comment by diogobaeder** [comment]
Interesting addition, I agree that this would make the example easier to read. "var" and "let" seem like reserved words, and not arbitrary values which you want to replace, I think.

**Comment by harthur** [comment]
Thanks a bunch, having a pull request ready to go makes it a lot easier.

**Pull request merged**
