### PR TITLE
Changes default directory to "."

### PR DESCRIPTION
**Pull request by jeremyckahn**
This Pull Request changes the default search path from `*` to `.`.  The former causes errors on OS X:

```
$: search 'foo' -r

fs.js:679
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '*'
    at Object.fs.lstatSync (fs.js:679:18)
    at replacizeFileSync (/Users/jeremyckahn/Sites/node/replace/replace.js:110:22)
    at module.exports (/Users/jeremyckahn/Sites/node/replace/replace.js:53:13)
    at Object.<anonymous> (/Users/jeremyckahn/Sites/node/replace/bin/search.js:11:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

This change allows users to omit the path and still get useful results.

### CODE REVIEW

**Comment by harthur** [comment]
Tough one, because if you leave out the `-r`, `.` does nothing. I'll think about it.

**Comment by jeremyckahn** [comment]
Any thoughts on how move forward with this?  I feel that it's a pretty common use case to search the current working directory.

**Comment by harthur** [comment]
I agree that it's probably the most common usecase. But I don't think anyone wants to search `.` non-recursively. One option is to search `. -r` if you don't specify anything.

**Comment by jeremyckahn** [comment]
That seems like a good solution to me.  Is that the current behavior, or should I submit a Pull Request?

**Comment by jeremyckahn** [comment]
Looks like this is the current default behavior.  I've been using my own fork for a while, so I couldn't tell immediately.  I'll close this Pull Request, as it appears to be no longer relevant.  Thanks!

**Comment by harthur** [comment]
I'm confused. I don't think it's the default: https://github.com/harthur/replace/blob/master/bin/shared-options.js#L14

**Comment by jeremyckahn** [comment]
Whoops, you're right.  I was testing the wrong package entirely, hah.  Sorry about that.  I'll update this Pull Request with the default behavior you suggested when I have some time.

**Comment by jeremyckahn** [comment]
Alrighty, I implemented your suggestion.  Please take another look.  I'm happy to adjust the patch to meet  any coding standards I may have missed.

**Comment by harthur** [comment]
Merged. Thanks a bunch.

**Pull request closed without merging**
