### PR TITLE
added more files to ignore

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
For anyone else interested, you can use my module instead of this one:

``` bash
npm install -g niftylettuce-replace
```

I keep it updated and tested.

**Comment by niftylettuce** [comment]
Link to repo: https://github.com/niftylettuce/replace

**Comment by harthur** [comment]
Sorry, I didn't see this pull request because it was closed. Will merge your ignore changes.

**Comment by niftylettuce** [comment]
thx @harthur -- btw haters gonna hate, don't worry about it.  your module is also cross-platform if you think about it.  keep up the awesome work and don't be afraid to contribute some recipes to us at http://startupsupper.com

**Comment by harthur** [comment]
@niftylettuce Thanks, and thanks for the pull request.

**Pull request closed without merging**
